remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Aton Code
description: Personal blog
show_downloads: false

theme: jekyll-theme-hacker